version: '3.3'

services:
   mongo:
    image: mongo
    restart: always
    volumes:
      - ./data/mongo:/data/db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root